### PR TITLE
Request for an optional "Apply for an account with eduGAIN" button

### PR DESCRIPTION
**Pull request by Sae126V**
Resolves https://github.com/indigo-iam/iam/issues/522

Added an anchor tag with the content saying "Apply for an account with eduGAIN".

### CODE REVIEW

**Comment by Sae126V** [comment]
eduGAIN_Btn

[Sample on how it looks like]

**Comment by rmiccoli** [comment]
LGTM :+1:

**Review by rmiccoli — APPROVED** [review]
LGTM :+1:

**Comment by giacomini** [comment]
Not necessarily with this PR, but we should probably use the same terminology commonly found on web services: "sign up" or "register".

**Review by rmiccoli — CHANGES_REQUESTED** [review]
Enable the "Apply for an account with EduGAIN" button only if SAML is enabled.
e.g. `<c:if test="${loginPageConfiguration.samlEnabled}">`

**Comment by Sae126V** [comment]
> Enable the "Apply for an account with EduGAIN" button only if SAML is enabled. e.g. `<c:if test="${loginPageConfiguration.samlEnabled}">`

Make sense. The will be visible only if SAML is enabled now.

**Review by rmiccoli — APPROVED** [review]

**Comment by enricovianello** [comment]
I think there's not only EduGAIN as a SAML provider. If you configured another SAML remote provider you'll see a non sense button with the label "Apply for an account with EduGAIN" or am I wrong? And if we add this button for each OIDC/SAML provider configured the login page could contain lots of buttons. Probably we need to add a configuration parameter for each SAML endpoint configured that enables or not its own, specific "Apply for an account with ..." button.

**Pull request merged**
