### PR TITLE
INDIAM-125: Ensure users cannot share an email address

### PR DESCRIPTION
**Pull request by andreaceccanti**

### CODE REVIEW

**Comment by andreaceccanti** [comment]
test this please

**Comment by andreaceccanti** [comment]
test this please

**Comment by andreaceccanti** [comment]
test this please

**Comment by marcocaberletti** [comment]
In the file newuser.html, the "iam-email-available-validator" has not been added to email field.
I've tried to insert a new user with duplicated email and after submit, the error of duplicated mail is correctly returned.
Maybe, also this form can be harmonized with others user form.

**Comment by andreaceccanti** [comment]
Ok, didn't see this before merging the PR. Will fix this in the develop branch

**Pull request merged**
