### PR TITLE
WIP: Support for multi-factor authentication through authenticator app #418

### PR DESCRIPTION
**Pull request by sam-glendenning**
# Overview
This adds the option of enabling multi-factor authentication through an authenticator app on an IAM account. This is designed to be flexible so that the user can enable or disable it at their will. The additional verification step kicks in after username and password authentication has taken place. At this stage, the user is "pre-authenticated" - they still cannot access the rest of the application. They are redirected to a verification page, whereby they enter a TOTP or a recovery code to be granted full authentication. 

# Documentation
- [Proposal document (constructed September-December 2021)](https://docs.google.com/document/d/1VOaE_lveJQXH_5tXweNDg3fb1E_R3-Npj3rDbcMZPgI/edit?usp=sharing)
- [Feature list](https://docs.google.com/document/d/1BXXfh_PxinDz1p954OTlApGvkY4fiR_773K-rMTI0l0/edit?usp=sharing)
- [README](https://drive.google.com/file/d/1iiJov__adosvQipgGlx6AM2aWqwhEQxQ/view?usp=sharing)
- Step by step guide [DOC](https://docs.google.com/document/d/1mADF4jWEN648pcv4EoMrbOypIvKzzPlK/edit?usp=sharing&ouid=109162302968999207387&rtpof=true&sd=true) and [PDF](https://drive.google.com/file/d/11JTeTAbtXibHtwA07i0eyhHcT4qHpTjK/view?usp=sharing)
- [Graphical release plan (constructed with ProductPlan in January 2022) (timeline out of date but relevant in terms of features)](https://drive.google.com/file/d/1ooEW7o8UoMQ59PjZYSsGjGw7i6xuBDkJ/view?usp=sharing)
- [Remaining questions and best practices](https://docs.google.com/document/d/1AT34O6UZ12jVBZmzVREfFCwyYvt2hx7XIBynvIvH7CE/edit?usp=sharing)

# Screenshots
**Verify page**
image

**Multi-factor settings button**
mfa settings button

**Multi-factor settings menu**
image

**Enabling multi-factor via a QR code and authenticator app**
image

**Display of recovery codes**
image

### CODE REVIEW

**Comment by sam-glendenning** [comment]
@enricovianello based on the time I have left, I'm going to mark this as Ready for review now. This will allow us to move my work from my IAM fork into the IAM repo proper. 

1. I have commented as much code as I can and fixed any failing tests that relate to MFA.
2. Current failing tests are few and seem to relate to OAuth functionality. I didn't directly touch these files during development but they are failing due to the introduction of the `ExtendedAuthenticationToken` replacing `UsernamePasswordAuthenticationToken` as the default authentication object. 
3. Not all of the MFA work I have done has been fully tested. The existing tests cover everything besides the integration of MFA into the OAuth2 login process. 

Tomorrow, I will endeavour to finish off any remaining documentation and send it to you and Francesco. I will also add links to it in this PR and will include a wider amount of information relating to all the features that have been tackled and what is remaining.

**Comment by sam-glendenning** [comment]
# Feature list as of 11/03/2022

## Implemented
- Authenticator app working for local IAM authentication only
- Multi-factor settings menu on dashboard
- OAuth2 integration with IAM clients
- Additional information passed to IAM clients in the form of an `amr` claim in the OAuth2 id_token (see [RFC 8176](https://datatracker.ietf.org/doc/html/rfc8176))
- Recovery codes as backup to TOTP

## Not yet implemented
- Integration with external identity providers
- Encryption and decryption of MFA secrets and recovery codes
- Support for MFA customisation by IAM admins (includes enable and disable feature, right now MFA is enabled permanently)
- _Optional_: Support for hardware token as another factor of authentication, e.g. [YubiKey](https://www.yubico.com/)

**Comment by giacomini** [comment]
Thanks, Sam, for your nice work and all the best for your next challenge.

**Comment by sam-glendenning** [comment]
> Thanks, Sam, for your nice work and all the best for your next challenge.

Thanks Enrico, just working on one final document to add to this PR and then I'll forward all the documentation in an email to you and Francesco when I'm done.

**Comment by rmiccoli** [comment]
Superseded by #662

**Pull request closed without merging**
